"""Build the September 30 researched edition from the verified current snapshot."""
import json
from pathlib import Path
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo

BASE = Path(__file__).resolve().parents[1]
s = json.loads((BASE/'work/daily-run/snapshot.json').read_text())
c = s['context']
now = datetime.now(timezone.utc)
sources = {}
def source(key, title, url, date, finding, kind='Official team report'):
    sources[key] = dict(title=title,url=url,date=date,kind=kind,finding=finding)
source('sleeper','Sleeper live league snapshot','https://api.sleeper.app/v1/user/coffero',c['fetched_at'],'All three leagues, scoring, reserves, starters, opposing rosters, transactions and snapshot observations reviewed. Observations establish roster changes, not necessarily trades.','Live league data')
source('was','Washington Wednesday injury report','https://www.commanders.com/news/commanders-colts-week-4-injury-report','2026-09-30','Daniels (elbow) and Okonkwo (hamstring) limited; Rachaad White did not practice. Final Sunday status is pending.')
source('hou','Houston Wednesday injury report','https://www.houstontexans.com/news/week-4-injury-report-texans-vs-cowboys','2026-09-30','Collins limited with hamstring injury. Page has an inconsistent older updated-date field; its Week 4 Wednesday table and September 30 publication are used.')
source('lac','Chargers Wednesday injury report','https://www.chargers.com/news/seahawks-injury-report-week-4','2026-09-30','McConkey limited with a foot injury. This is a new report, not last week’s rib designation. Sunday kickoff is 4:25 p.m. ET.')
source('pit','Steelers final Thursday-game injury report','https://www.steelers.com/news/week-4-injury-report-browns','2026-09-30','Dowdle is out. Warren had 17 carries and three catches last week. Cleveland is missing two interior linemen; Pittsburgh has secondary injuries. The article’s Sunday wording conflicts with the NFL Thursday schedule; use NFL kickoff.')
source('nyj','Jets Wednesday injury report','https://www.newyorkjets.com/news/jets-injury-report-week-4-vs-bears-wednesday-09-30-2026','2026-09-30','Hall did not practice with a quad injury; no final game designation yet.')
source('waiver','FantasyPros Week 4 waiver analysis','https://www.fantasypros.com/2026/09/fantasy-football-waiver-wire-rankings-pickups-week-4-2026//?amp=1','2026-09-28','Allen has conditional opportunity. Gordon played 61 snaps with 17 carries and three catches after Achane’s injury; Wright’s return could change the split. National availability is not league ownership.','Analyst usage and waiver review')
source('ranks','Mayo Media Week 4 rankings','https://mayomedia.substack.com/p/2026-week-4-fantasy-football-rankings','2026-09-30; rankings updated 2026-09-29','Half-PPR opinion: Hurts above Stroud; Mahomes above Nix; Jones slightly above Herbert. Johnson above Kraft; Burden above McConkey. These are not custom-scoring projections. Injury predictions yield to newer official reports.','Analyst rankings')
source('second','Independent Week 4 rankings','https://fantasy-rankings.com/week-4','2026-09-29 QB/TE/RB; 2026-09-30 WR','Also prefers Hurts to Stroud and Jones to Herbert. Fannin valuation differs sharply from Mayo; both prefer McBride to Kincaid. Treat rank disagreement as uncertainty.','Analyst rankings')
source('value','CBS Week 4 trade values','https://mauth.cbssports.com/fantasy/football/news/dave-richards-week-4-trade-chart-and-rest-of-season-fantasy-football-rankings-help-you-win-now/','2026-09-29; checked 2026-09-30','Provides separate one-QB and two-QB values. Backup QBs carry little one-QB trade value. Short-term injury opportunity is not equal to season-long starter value. No chart is an acceptance probability.','Rest-of-season opinion')
source('schedule','NFL Week 4 schedule and game statuses','https://fantasy-www.nfl.com/news/nfl-week-4-injury-report-player-statuses-for-all-16-games','2026-09-30','PIT/CLE Thursday October 1 at 8:15 p.m. ET; IND/WAS Sunday 9:30 a.m.; ATL/NO Monday 8:15 p.m. All 32 teams scheduled. No Week 4 game has started at research time.','NFL report')

def move(action,pid,title,reason,cost,refs,confidence='Conditional'):
    return dict(action=action,id=pid,title=title,reason=reason,cost=cost,sources=refs,confidence=confidence,drop_id=None)
plans = {
'1403096266736422912':[
move('Monitor','6904','Review Hurts versus your chosen Stroud start','Both ranking checks favor Hurts, but your lineup was built with Claude’s custom-scoring model, whose projections were not available for this review.','Keep the chosen Stroud baseline pending a direct projection comparison. Six-point passing TDs and opponent assumptions may explain the difference; this is an alternative to review, not a verified improvement.',['ranks','second','sleeper'],'Conditional'),
move('Start','8228','Keep Warren in an RB slot Thursday','Dowdle is out; Warren’s recent workload supports the start.','RB placement preserves Sunday FLEX flexibility. Check Thursday inactives before 8:15 p.m.; retain Barkley and Brown elsewhere in the lineup.',['pit','schedule'],'Strong'),
move('Monitor','11635','Hold McConkey; keep Burden provisionally','McConkey’s foot limited Wednesday practice. The WR comparison is close and analysts disagree.','Keep injury cover without a claim. Revisit before Burden’s 1 p.m. kickoff; waiting until McConkey’s later game could remove that alternative.',['lac','ranks','second'],'Conditional'),
move('Hold','7002','Lean Johnson at TE, preserve Kraft cover','The two ranking checks favor Johnson.','Monday timing creates replacement risk. If Johnson develops an issue, decide on Kraft before his Sunday 1 p.m. lock. No extra TE claim needed.',['ranks','second','schedule'],'Lean')],
'1385050179488460800':[
move('Hold','11576','Allen is acquired; treat FLEX as conditional','Hall missed Wednesday practice, supporting an opportunity for Allen if Hall sits.','No second claim or Badie drop. If Hall is cleared, compare Kincaid and receiver alternatives before Sunday 1 p.m. Preserve Allen as depth rather than paying a trade premium.',['nyj','waiver','sleeper']),
move('Monitor','7569','Prepare Egbuka as Collins’s replacement','Collins remains limited with a hamstring issue; Wednesday participation is not clearance.','Keep Collins provisionally if active without a reported restriction. If unavailable, use Egbuka before both games lock Sunday 1 p.m.; Odunze is another owned option. No roster-space cost.',['hou','ranks','second']),
move('Start','4046','Keep Mahomes over Nix','Both reviewed QB lists favor Mahomes this week.','Four-point passing TDs and minus-one interceptions apply here. Nix is injury/bye cover; a third QB would use scarce bench space.',['ranks','second','sleeper'],'Lean'),
move('Hold','8130','Keep McBride at TE after the Bowers deal','The completed trade changed your depth: Kincaid, Montgomery and Kyren arrived; Bowers and Irving left.','McBride stays at TE. Kincaid covers TE or a conditional FLEX opening; do not add another TE while Goedert is an injury uncertainty.',['sleeper','second'],'Strong')],
'1360286127205912576':[
move('Start','5870','Keep Jones as the provisional QB','Both reviewed lists put Jones ahead of Herbert, although neither is a strong weekly option.','The completion bonus and 45 yards per two passing points can narrow that gap; no custom projections are available. Recheck before London’s 9:30 a.m. kickoff. Keep Herbert as cover.',['ranks','second','sleeper','schedule'],'Lean'),
move('Start','12506','Keep Fannin at TE Thursday','Fannin is absent from Cleveland’s final injury designations; Okonkwo was limited Wednesday.','Analysts disagree on Fannin’s ceiling. Keep him in TE, check final inactives, and avoid paying for a redundant rental.',['pit','was','second','ranks'],'Lean'),
move('Hold','12495','Keep Gordon as RB depth','The recent Miami workload makes him worth holding; Wright can still change the backfield split.','Do not automatically replace Love or Croskey-Merritt. Compare usage news before the early Washington lock; Gordon’s later game reduces flexibility. Miami’s Week 6 bye means he is not permanent bye cover.',['waiver','schedule'],'Conditional'),
move('Hold','5927','Keep McLaurin in FLEX with QB news on watch','The current roster contains McLaurin and Wilson, with Lamb in the other WR slot. Washington’s quarterback availability remains unsettled.','Retain Malik Washington as receiver cover. Make the Washington decision before 9:30 a.m.; there is no immediate need for another trade after the recent roster changes.',['sleeper','was','schedule'],'Conditional')]
}
notes = {
'1403096266736422912':('Six-point passing TDs, full PPR, three WR and Superflex; no TE premium.','No trade proposed. All five rivals have multiple QBs and established TE alternatives; Stroud or Kraft alone does not justify demanding a premium WR. realzavierR now owns Garrett Wilson and Allen; johnlucamigaldi owns Fannin. Phil the Fur added Gordon and released Judkins. Evaluate available Judkins for future depth, but no supported upgrade over this week’s current RB core warrants a drop. Jones is free but would be a fifth QB.','Keep Daniels pending official clearance; Coleman remains reserve depth. Keep PIT against Cleveland, noting opposing line absences and Pittsburgh secondary injuries. Retain Shrader pending final reports.'),
'1385050179488460800':('Full PPR, four-point passing TDs, minus-one interceptions and yardage bonuses; two FLEX slots, no TE premium.','No trade proposed. Your completed Bowers/Irving deal already produced Kyren, Montgomery and Kincaid. The counterparty now owns Bowers/Kraft, so is not a Kincaid buyer. Hall’s manager MagicMax5 could value Allen, but has Kittle/Johnson/Waller/Higbee and Allen fills your own FLEX: a speculative TE swap adds little. Jones is free but Mahomes/Nix cover QB. Gordon and Fannin are owned elsewhere.','Use Gibbs/Kyren at RB and Montgomery in FLEX. Keep PIT for Thursday with secondary-injury risk; keep Bates. Coleman is in reserve; Goedert’s cached Doubtful tag is not a fresh medical clearance.'),
'1360286127205912576':('Full PPR, four-point passing TDs, 0.1 per completion and one point per 22.5 passing yards plus yardage bonuses; one FLEX.','No trade proposed. Gordon is already yours; Bo Dix owns Wright and Kendre Miller, so neither is a waiver option. Costco added Jennings and still has Purdy/Darnold plus Johnson/Warren. giannispetrizzo has Lawrence despite Mayfield’s injury; Herbert is not an obvious premium trade chip there. Preserve RB depth rather than swap Gordon for redundant QB/TE cover.','Keep Love/Croskey-Merritt at RB and Lamb/Wilson at WR provisionally. Retain MIN versus Miami and Shrader. Williams remains a recovery stash, not a cleared QB; confirm his next official report before considering activation.')
}
r = dict(name='Binocular',user=c['user'],season=str(c['season']),week=int(c['nfl_week']),reviewed_at=now.astimezone(ZoneInfo('America/Detroit')).date().isoformat(),updated_at=now.isoformat(),valid_until=(now+timedelta(hours=24)).isoformat(),expires_after='2026-10-06',scope='September 30 Week 4 review. Live ownership and dated sources checked; Sunday/Monday game designations remain pending. The user confirmed the current lineup was built with Claude; it is preserved as the chosen baseline. Claude model outputs were not inspected or validated here. No custom-scoring projections or moves executed.',sources=sources,leagues={},candidates=[dict(name=n,role='Ownership and role watch',sources=['sleeper','waiver']) for n in ['Daniel Jones','Braelon Allen','Ollie Gordon','Jaylen Wright','Kendre Miller','Harold Fannin','Juwan Johnson','Quinshon Judkins']],changes=['Replaced obsolete claims and departed-player advice with current rosters.','Jacked Pine: preserve chosen Stroud lineup; flag Hurts comparison and confirm Warren Thursday case.','Netanyahu Ball: completed Bowers trade and Allen acquisition reflected; Collins contingency added.','MSU: Jones/Gordon additions reflected; Fannin Thursday plan and Washington kickoff decisions reviewed.'])
for league in c['leagues']:
    lid=league['id']; team=next(t for t in league['tracking']['teams'] if t['owner_id']==c['user_id'])
    players={p['id']:p for p in team['players']}; starters=list(team['starters'])
    scoring,trade,watch=notes[lid]
    lineup=[dict(slot=slot,id=pid,name=players[pid]['name'],position=players[pid]['position'],team=players[pid]['team'],note='User-selected current lineup; see research alternatives, injury conditions and kickoff notes.') for slot,pid in zip(team['slots'],starters)]
    moves=plans[lid]
    r['leagues'][lid]=dict(name=league['name'],headline=moves[0]['title'],strategy='Retain useful cover; make injury-dependent decisions before the relevant kickoff.',scoring_note=scoring,scoring_baseline=league['scoring'],slots_baseline=league['slots'],roster_ids=sorted(p['id'] for p in league['roster']),lineup=lineup,calls=[dict(kind=m['action'],title=m['title'],reason=m['reason'],confidence=m['confidence'],sources=m['sources'],recheck=m['cost']) for m in moves],lineup_notes=[dict(title='Trade and waiver review',body=trade,sources=['sleeper','value','waiver']),dict(title='Other lineup and reserve decisions',body=watch,sources=['sleeper','schedule','pit']),dict(title='Timing and uncertainty',body='No Week 4 byes or games already locked. Thursday players lock October 1 at 8:15 p.m. ET. Sunday/Monday final inactives are not yet available. Never treat a blank cached injury flag as proof of health.',sources=['schedule'])],player_moves=moves,trades=[],watch=watch)
    assert len(lineup)==len(team['slots']) and len(set(starters))==len(starters)
    for p in lineup:
        allowed={'FLEX':{'RB','WR','TE'},'SUPER_FLEX':{'QB','RB','WR','TE'}}.get(p['slot'],{p['slot']})
        assert p['position'] in allowed
dest=BASE/'work/research-2026-09-30.json'
dest.write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
print(dest)
