import json
from pathlib import Path
R=Path('outputs/Sleeper Brief.app/Contents/Resources')
sources={
'sleeper':{'title':'Sleeper API documentation','url':'https://docs.sleeper.com/','date':'Checked Sep 15, 2026','kind':'Platform documentation','finding':'Read-only league data. Trending counts measure adds; player metadata is cached daily. Display week can differ from NFL week.'},
'qb':{'title':'ClutchPoints · Week 2 QB rankings','url':'https://clutchpoints.com/fantasy-sports/fantasy-football-quarterback-rankings-week-2-2026','date':'Sep 15, 2026','kind':'Analyst rankings','finding':'Ranks Caleb Williams 7th, Bo Nix 10th, Patrick Mahomes 17th and Baker Mayfield 20th. These are ordinal opinions, not projections for your custom scoring.'},
'flex':{'title':'Pat Fitzmaurice · Week 2 PPR flex','url':'https://www.fantasypros.com/nfl/rankings/pat-fitzmaurice.php?scoring=PPR&week=2','date':'Sep 15, 2026','kind':'Analyst rankings','finding':'Etienne is ahead of Reed; Kraft is ahead of Juwan Johnson. Stevenson versus Etienne is closer and varies by analyst. Keep that uncertainty visible.'},
'wr':{'title':'Pat Fitzmaurice · Week 2 PPR receivers','url':'https://www.fantasypros.com/nfl/rankings/pat-fitzmaurice.php?position=WR&scoring=PPR&week=2','date':'Sep 15, 2026','kind':'Analyst rankings','finding':'Adams is WR23, Golden WR35 and Reed WR45 in this ranking. This supports Adams over Reed without treating a single list as certainty.'},
'ladd':{'title':'Chargers · McConkey injury update','url':'https://www.chargers.com/news/ladd-mcconkey-injury-fantasy-jm-harbaugh-week-1','date':'Sep 14, 2026','kind':'Official team report','finding':'Jim Harbaugh described McConkey as day-to-day with a rib injury. That is not clearance to play in Week 2.'},
'douglas':{'title':'DraftKings Network · Caleb Douglas usage','url':'https://dknetwork.draftkings.com/2026/09/14/is-caleb-douglas-a-top-week-2-waiver-pickup/','date':'Sep 14, 2026','kind':'Reported usage','finding':'Douglas played 91% of snaps and drew seven targets, catching five for 94 yards. Malik Washington drew eight targets; adding Douglas does not automatically make Washington expendable.'},
'black':{'title':'49ers · Week 1 game recap','url':'https://www.49ers.com/news/49ers-open-2026-with-27-7-win-over-rams-in-melbourne-takeaways-from-larvssf','date':'Sep 10, 2026','kind':'Official team report','finding':'Kaelon Black had 14 carries for 65 yards. Meaningful involvement makes him a bench candidate; one game does not establish a weekly starting workload.'},
'loveland':{'title':'DraftKings Network · Loveland vs. Kmet','url':'https://dknetwork.draftkings.com/2026/09/15/is-cole-kmet-not-colston-loveland-the-fantasy-te-to-own-in-chicago/','date':'Sep 15, 2026','kind':'Reported usage','finding':'Loveland had an 87% snap share and 35 routes despite no receptions. Kmet ran 19 routes. Opportunity supports holding Loveland rather than chasing the Week 1 touchdown.'},
'golden':{'title':'DraftKings Network · Matthew Golden role','url':'https://dknetwork.draftkings.com/2026/09/15/is-matthew-goldens-fantasy-breakout-finally-here/','date':'Sep 15, 2026','kind':'Reported usage','finding':'Golden recorded 12 targets and 40 routes with an 82% snap share. Keep the upside, while allowing for Week 1 game-script inflation.'},
'coker':{'title':'Panthers · Coker’s Week 1 performance','url':'https://www.panthers.com/news/jalen-coker-continues-his-streak-of-career-games-with-week-1-performance','date':'Sep 13, 2026','kind':'Official team report','finding':'Coker produced 138 receiving yards and two touchdowns. His availability deserves attention even when a trending-only shortlist misses him.'},
'coker_health':{'title':'Panthers · Coker ankle update','url':'https://www.panthers.com/news/monday-brew-dave-canales-addresses-run-defense-coker-on-precautionary-boot-and-more','date':'Sep 14, 2026','kind':'Official team report','finding':'Coker wore a precautionary boot after rolling his ankle. He expected not to miss time, but the weekly practice and game-status reports remain necessary.'},
'dst':{'title':'FantasyPros · Week 2 defense streamers','url':'https://www.fantasypros.com/2026/09/lets-stream-defenses-week-2-2026-fantasy-football/','date':'Week 2, checked Sep 15','kind':'Analyst rankings','finding':'Ranks Tampa Bay 1st, Philadelphia 2nd, San Francisco 4th, Denver 8th and Minnesota 21st. Generic projected points are not recalculated for your leagues.'},
'value':{'title':'FantasyPros · Week 2 redraft trade values','url':'https://www.fantasypros.com/2026/09/fantasy-football-trade-value-chart-week-2-2026/','date':'Sep 15, 2026','kind':'Analyst valuation','finding':'Use as a rough negotiation check, not an acceptance probability. The chart separates 1QB and 2QB values; package totals alone do not prove a trade is fair.'},
'pfn':{'title':'PFSN · Week 2 waiver analysis','url':'https://www.profootballnetwork.com/fantasy-football/waiver-wire-week-2-2026/','date':'Sep 13, 2026','kind':'Analyst usage review','finding':'Vele benefits from Tyson’s absence. Allgeier’s early role complicates Love’s workload. These are role-sensitive situations, not guaranteed weekly production.'},
'apple':{'title':'Apple · Sidebar guidance','url':'https://developer.apple.com/design/human-interface-guidelines/sidebars','date':'Checked Sep 15, 2026','kind':'Design guidance','finding':'Keep navigation shallow and let people hide the sidebar to make room for content.'},
'access':{'title':'Apple · Accessibility guidance','url':'https://developer.apple.com/design/human-interface-guidelines/accessibility','date':'Checked Sep 15, 2026','kind':'Design guidance','finding':'Support legible text, adequate contrast, keyboard interaction and status labels that do not depend on color alone.'},
'product':{'title':'FantasyPros · My Playbook','url':'https://www.fantasypros.com/nfl/myplaybook/intro','date':'Checked Sep 15, 2026','kind':'Product comparison','finding':'League-aware lineup, waiver and trade tools are a useful reference. Binocular should expose the evidence and roster cost behind a proposed move.'}
}
def call(kind,title,reason,confidence,refs,check):return dict(kind=kind,title=title,reason=reason,confidence=confidence,sources=refs,recheck=check)
leagues={
'1403096266736422912':{'name':'Jacked Pine','headline':'Add QB cover before shopping for a trade.','strategy':'Six-team superflex rewards starter quality. With Hurts and Daniels already starting, a third quarterback protects two lineup slots; marginal receiver depth is easier to replace.',
'calls':[
call('Waiver','Add Brock Purdy; drop Josh Downs','Purdy was unrostered in the full league snapshot, beyond the trending list. Keep Hurts and Daniels starting. Purdy is injury and bye-week cover, not an automatic replacement.','Strong roster fit',['sleeper','value'],'Confirm Purdy is still unrostered and Downs is still on your bench.'),
call('Lineup','Start Etienne over Reed in a FLEX slot','Retain Stevenson in the other FLEX for now. The PPR flex comparison favors Etienne over Reed; the Stevenson–Etienne ordering is less settled.','Lean',['flex'],'Recheck injuries and updated PPR rankings before kickoff.'),
call('Injury','Keep McConkey on the watch list','Use a healthy alternative until the rib injury is clarified. Godwin is a viable alternative to review; do not interpret a cached status as game-day clearance.','Monitor',['ladd'],'Read the final Chargers injury report and inactive list.'),
call('Trade','Hold: the free QB solves the immediate need','An optional opening inquiry is Reed + Juwan Johnson for Colston Loveland with zavierR. Both sides own those players. It is a consolidation idea, not a must-send offer; zavierR may reject two bench pieces.','Exploratory',['value'],'Purdy first. Do not add a core starter merely to complete this deal.')],
'watch':['Brock Purdy','Jalen Coker','TB','SF','Caleb Douglas'],
'scoring_note':'6-point passing TDs and −2 interceptions. A three-passing-TD game earns six more points than in a 4-point league, all else equal.'},
'1385050179488460800':{'name':'Netanyahu Ball','headline':'Use the bench to improve this week’s starters.','strategy':'Your active roster has two kickers and three running backs. Replacing a spare kicker with useful RB depth is a cleaner first move than weakening your starting core.',
'calls':[
call('Lineup','Start Adams over Reed; lean Nix over Mahomes','The receiver ranking favors Adams. Two early QB lists favor Nix, but your yardage bonuses can affect close comparisons; this is a lean, not a custom projection. Keep Golden as a developmental hold.','Lean',['wr','qb','golden'],'Recheck late-week rankings, health and weather.'),
call('Waiver','Add Kaelon Black; drop Harrison Mevis','Keep Jake Bates. Black provides RB depth without sacrificing a skill-position player. If immediate WR depth matters more, healthy Coker is the alternative for the same roster spot—these are mutually exclusive first moves.','Strong roster fit',['black','coker','coker_health'],'Verify both availability and Coker’s ankle status. Do not assume a claim clears.'),
call('Reserve','Keep Bowers visible in your plan','The live roster lists Brock Bowers in reserve; the original brief omitted him. Keep Goedert active pending Bowers’ return rather than adding a third tight end merely because he is trending.','Roster fact',['sleeper'],'Check IR eligibility and Bowers’ return status before activating him.'),
call('Trade','Optional: Reed for Kyle Monangai','BabyMamaPayment owns Monangai. He would provide cover behind your Swift; the other manager gets receiver depth. Similar rough chart values make it a discussion, not proof of mutual benefit. Prefer the free RB addition first.','Exploratory',['value'],'Do not sacrifice Golden or add a starter to buy backup insurance.')],
'watch':['Kaelon Black','Jalen Coker','Caleb Douglas','Braelon Allen','Devaughn Vele'],
'scoring_note':'4-point passing TDs, −1 interceptions, plus passing/rushing/receiving yardage bonuses. The short “1QB/PPR” label did not capture all of this.'},
'1360286127205912576':{'name':'MSU Munches v2','headline':'Keep Loveland. Improve the edges of the roster.','strategy':'In a 16-team league, useful depth is scarce. One tight end can be enough when he has a strong role; the old count-based “thin at TE” flag was not a reason to sell a starting receiver.',
'calls':[
call('Lineup','Keep Caleb Williams and Loveland starting','Early QB rankings favor Caleb over Baker. Loveland’s routes support patience. Your completion and yardage scoring may narrow the QB gap; do not treat standard QB ranks as exact expected points.','Lean',['qb','loveland'],'Caleb and Baker share a Week 10 bye in the reviewed schedule; plan separate cover later.'),
call('Waiver','Add Caleb Douglas; drop Tre Tucker','Douglas offers a plausible long-term role upgrade. Keep Malik Washington for now: his own Week 1 target volume argues against cutting him automatically. Do not rush Douglas into FLEX against San Francisco.','Medium',['douglas'],'Confirm Douglas remains available; preserve the rest of your starting core.'),
call('Defense','Stream Tampa Bay for Minnesota; SF is the fallback','Both were unrostered in the checked snapshot. The defense ranking strongly favors these Week 2 matchups. Use the existing defense slot rather than cutting an upside bench player.','Lean',['dst'],'Check availability and the league’s defense scoring before claiming.'),
call('Trade','No urgent TE trade','Team 5 owns Andrews and Kelce; that alone does not make either an upgrade on Loveland. A Tucker-for-Andrews inquiry is conceivable on rough values, but I prefer the Douglas waiver move and keeping WR depth.','Hold',['loveland','value'],'Do not trade Michael Wilson or DJ Moore merely to fix a roster-count deficit.')],
'watch':['Caleb Douglas','TB','SF','Kaelon Black','Braelon Allen','Devaughn Vele','Jalen Coker'],
'scoring_note':'+0.1 per completion, 1 passing point per 22.5 yards, 4 per passing TD, −1 per interception, plus yardage bonuses. At 25 completions and 300 passing yards, that is about 3.83 extra points versus 0 completion points and 1 per 25 yards, before bonuses.'}
}
candidates=[{'name':n,'role':role,'sources':refs} for n,role,refs in [
('Brock Purdy','Superflex QB cover',['value']),('Bo Nix','QB alternative',['qb']),('Tyler Shough','Passing-volume watch',['pfn']),('Jordan Love','QB depth',['value']),('Jalen Coker','WR upside · ankle watch',['coker','coker_health']),('Caleb Douglas','Long-term WR role',['douglas']),('Devaughn Vele','Short-term WR opportunity',['pfn']),('Kaelon Black','RB depth / contingent upside',['black']),('Braelon Allen','Breece Hall insurance',['pfn']),('Tyler Allgeier','Early RB workload',['pfn']),('Michael Mayer','Temporary TE cover',['pfn']),('TB','Week 2 defense stream',['dst']),('SF','Week 2 defense stream',['dst'])]]
research={'name':'Binocular','user':'coffero','season':'2026','week':2,'reviewed_at':'2026-09-15','expires_after':'2026-09-22','scope':'Manually researched Week 2 edition. Refresh updates Sleeper data, not these articles or analyst calls. Recheck injury reports and availability before acting.','sources':sources,'leagues':leagues,'candidates':candidates}
(R/'research.json').write_text(json.dumps(research,indent=2,ensure_ascii=False))
(R/'research.js').write_text('window.RESEARCH = '+json.dumps(research,ensure_ascii=False)+';\n')
