import json
from pathlib import Path
from datetime import datetime,timezone,timedelta
s=json.load(open('work/daily-run/snapshot.json'));c=s['context'];r=json.load(open('outputs/daily-edition.json'))['research'];P=json.load(open('work/daily-cache/players.json'));r['sources']={}
def src(k,title,url,finding,date='2026-09-28',kind='Research'):
 r['sources'][k]=dict(title=title,url=url,date=date,kind=kind,finding=finding)
src('sleeper','Sleeper live league snapshot','https://docs.sleeper.com/','All-team ownership, roster slots, scoring and completed/failed transactions checked at the snapshot timestamp.',kind='Live league data')
src('monday','Eagles–Bears official injury report','https://www.philadelphiaeagles.com/news/eagles-at-bears-injury-report-2026-nfl-week-3-monday-night-football-caleb-williams-saquon-barkley','Barkley available; Goedert and Caleb Williams ruled out. Bagent cleared protocol. Final inactive lists still pending.',date='2026-09-27; checked 2026-09-28',kind='Official team report')
src('ertz','Eagles elevate Zach Ertz','https://www.philadelphiaeagles.com/news/eagles-elevate-chance-campbell-zach-ertz-for-monday-night-football-chicago-bears-2026-nfl-regular-season-week-3','Ertz elevated for Monday. This creates a possible emergency TE option but does not guarantee snaps.',kind='Official team report')
src('waiver','NFL Week 4 waiver targets','https://amp.nfl.com/news/2026-nfl-fantasy-football-waiver-wire-week-4-te-juwan-johnson-rb-braelon-allen-headline-targets','Johnson and Braelon Allen headline the list. Daniel Jones is an early Week 4 streaming option against Washington despite a weak start; this is an analyst opinion.')
src('allen','Week 4 waiver outlook','https://www.si.com/fantasy/week-4-waiver-wire-targets','Braelon Allen benefits if Hall misses time with his thigh injury. Monitor updates rather than assume an absence.')
src('baker','NFL: Mayfield expected to miss at least three weeks','https://amp.nfl.com/news/buccaneers-qb-baker-mayfield-thumb-out-at-least-three-weeks-jalon-daniels','Thumb injury creates a multiweek quarterback need; rookie Jalon Daniels is expected to start for Tampa Bay.',kind='NFL injury report')
src('etienne','Etienne injury impact','https://sports.yahoo.com/articles/fantasy-football-injury-impact-travis-185102776.html','Etienne’s injury creates a potential opportunity for Kamara. Do not assume a fixed recovery timeline or guaranteed workload.')
src('trade','Trade baseline before Week 3 injuries','https://www.fantasypros.com/2026/09/fantasy-football-trade-value-chart-week-3-2026/','September 22 valuations predate the latest injuries and should not price offers today. Current ownership and role uncertainty take precedence.',date='2026-09-22; reassessed 2026-09-28')
ids=['1339','6826','11576','5870','7002','12506']
for l in c['leagues']:
 owners={p['id']:t['name'] for t in l['tracking']['teams'] for p in t['players']}
 for pid in ids:
  if not any(p['id']==pid for p in l['market']):
   p=P[pid];l['market'].append(dict(id=pid,name=p['full_name'],position=p['position'],team=p.get('team'),injury=p.get('injury_status'),owner=owners.get(pid)))
Path('work/daily-run/snapshot.json').write_text(json.dumps(s,ensure_ascii=False))
def m(action,pid,title,reason,cost,ss,confidence='Conditional',drop=None):
 return dict(action=action,id=pid,title=title,reason=reason,cost=cost,sources=ss,confidence=confidence,drop_id=drop)
for l in c['leagues']:
 a=r['leagues'][l['id']];t=next(t for t in l['tracking']['teams'] if c['user_id'] in [x['id'] for x in t['members']]);ps={p['id']:p for p in t['players']}
 a.update(roster_ids=sorted(p['id'] for p in l['roster']),scoring_baseline=l['scoring'],slots_baseline=l['slots'],trades=[])
 if l['name']=='Jacked Pine':
  moves=[m('Hold','4866','Keep Barkley and Hurts ready for tonight','Barkley is available on the official report; both players already occupy your Monday slots.','Recheck final inactives before 8:15 p.m. ET. Sunday players are locked.',['monday','sleeper'],'Strong'),m('Hold','7002','Keep Johnson; reassess next week’s TE starter','Johnson is already yours and appears among the early Week 4 waiver priorities.','No claim required. Kraft’s Week 3 points cannot be replaced retrospectively.',['waiver','sleeper'],'Hold'),m('Monitor','7543','Remove the old Etienne start recommendation','His new injury makes the September 25 FLEX advice obsolete; Pollard remained in your actual lineup.','Preserve Warren, who replaced Stevenson, as depth. Await recovery news before a drop or injury discount trade.',['etienne','sleeper'],'Strong'),m('Monitor','4892','Mayfield is injured depth, not a Week 4 replacement','The new thumb injury joins Daniels’ absence; Hurts and Purdy remain your starting QB pair.','Do not pay for a third QB urgently in this six-team league. Review reserve eligibility and upcoming byes before dropping injured depth.',['baker','sleeper'],'Strong')]
  headline='Keep your Monday starters; reset injury and TE plans for Week 4.';strategy='Warren replaced Stevenson, Mayfield was added, and Coleman is in reserve. Sunday decisions are finished; the older Etienne FLEX lean is retired.';watch=['Saquon Barkley','Baker Mayfield','Travis Etienne'];score='PPR and six-point passing TDs reward keeping Hurts/Purdy intact. Current lineup is a record of Week 3, not permission to move locked players.'
  tn='No trade offer today. Rival rosters already contain multiple QBs and useful TEs; selling Johnson into a deep six-team market or injured Etienne lacks a clear return. Free-agent Allen is worth watching after Hall news, but do not cut valuable cover on an unconfirmed role.'
 elif l['name']=='Netanyahu Ball':
  moves=[m('Hold','PHI','Keep Philadelphia defense for Monday','Williams is ruled out and Chicago’s quarterback situation changed during the week.','Already rostered and starting; no acquisition needed. No guaranteed defensive score.',['monday','sleeper'],'Hold'),m('Hold','4035','Hold Kamara as the Saints backfield changes','Etienne’s injury improves the case for keeping your existing veteran depth.','Do not sell cheaply before role and practice reports establish the workload. He cannot be inserted for Sunday points now.',['etienne','sleeper'],'Hold'),m('Add','11576','Early Week 4 claim: Allen for Badie','Allen is unrostered in this league; Hall’s injury makes him a supported contingency target.','One-for-one replacement for Badie when roster locks permit. Keep bid modest pending Hall news; not a guaranteed starter.',['allen','sleeper'],'Conditional','8208'),m('Sit','5022','Keep Goedert benched tonight','The Eagles officially ruled him out. Your McBride/Bowers slots are already settled from Sunday.','No need to acquire a fourth TE. Odunze cannot replace a locked Sunday FLEX player.',['monday','sleeper'],'Strong')]
  headline='Philadelphia plays tonight; hold Kamara and watch Allen on waivers.';strategy='MagicMax5 now has Coker and Johnson after trading Tucker and Warren to Maye Cook. Retire old partner assumptions. Collins remains in reserve; Coleman is now IR on the provider feed.';watch=['Alvin Kamara','Braelon Allen','Dallas Goedert'];score='PPR with yardage bonuses and no TE premium. Prioritize RB depth over another TE; Allen is a prospective Week 4 claim, not a Monday lineup move.'
  tn='No offer recommended. MagicMax5 has Kittle, Johnson and Waller, while Maye Cook added Warren; another TE is not an obvious need for either. Keep Kamara until the Saints rotation clarifies rather than pricing him using last week’s chart.'
 else:
  moves=[m('Add','1339','Urgent: consider Ertz for the empty Monday TE slot','The Helm/Marks-for-Fannin trade left your TE slot empty. Fannin already played; Ertz is unrostered and elevated for tonight with Goedert out.','Your 13-player roster is below its 14 active slots, so no drop appears needed. Only add if Sleeper permits immediate use, then start only after active confirmation. Kmet is also unrostered if Ertz is inactive; both are low-confidence emergency options.',['sleeper','ertz','monday'],'Conditional'),m('Add','5870','Queue Jones as Week 4 QB cover','Mayfield is expected to miss multiple weeks and Williams is out tonight; Jones is unrostered and gets Washington next week.','Use the remaining vacancy if available. If Ertz occupies it, replace Ertz after Monday locks release; retain Fannin. Do not replace Mayfield’s already-earned Week 3 score.',['baker','waiver','sleeper'],'Lean'),m('Hold','12506','Fannin is your Week 4 TE, not a retroactive Week 3 fix','The completed trade brought him in for Helm and Marks. His game has finished and your live TE slot remains empty.','Keep him rather than sacrificing the new acquisition for a one-night rental. Reassess Week 4 start rankings when available.',['sleeper'],'Strong'),m('Hold','11610','Keep Washington as receiver cover','He is already yours; avoid creating another position hole while resolving QB and TE.','Reserve bench space for injury and bye coverage. No additional trade required today.',['sleeper'],'Hold')]
  headline='Empty TE slot tonight; quarterback cover is the next priority.';strategy='The completed Fannin trade removed Helm and Marks. Ertz is a conditional Monday rental; Jones is an early Week 4 streamer. Neither has been added, and no lineup action has been submitted.';watch=['Zach Ertz','Daniel Jones','Baker Mayfield','Caleb Williams'];score='PPR, completion bonuses and enhanced passing-yard scoring increase the importance of an active Week 4 QB. These rules do not unlock Mayfield’s Sunday slot.'
  tn='No new trade recommended: available Jones can address QB cover without surrendering a starter. The Fannin trade already addressed TE long term. Braelon Allen and Juwan Johnson belong to other managers here; national waiver lists do not make them available.'
 a.update(headline=headline,strategy=strategy,watch=watch,scoring_note=score,player_moves=moves)
 a['calls']=[dict(kind=x['action'],title=x['title'],reason=x['reason'],confidence=x['confidence'],sources=x['sources'],recheck=x['cost']) for x in moves]
 a['lineup']=[]
 for slot,pid in zip(t['slots'],t['starters']):
  p=ps.get(pid)
  a['lineup'].append(dict(slot=slot,id=pid,name=p['name'] if p else 'Empty — Monday TE needed',position=p['position'] if p else slot,team=p.get('team') if p else None,note='Monday: check final active list' if p and p.get('team') in ['PHI','CHI'] else 'Empty: do not insert a player whose game is over' if not p else 'Already played — locked; not a new start recommendation'))
 a['lineup_notes']=[dict(title=x['title'],body=x['reason']+' '+x['cost'],sources=x['sources']) for x in moves]+[dict(title='Trade review',body=tn,sources=['trade','sleeper']),dict(title='Monday and Week 4 boundary',body='Only Monday players remain before 8:15 p.m. ET. Final inactives are not yet published at this review. Week 4 claims are provisional; this edition retains Sleeper’s current Week 3 and expires at the week boundary.',sources=['monday','sleeper'])]
r['candidates']=[dict(name=P[pid]['full_name'],role='Monday availability or early Week 4 watch; check league-specific call',sources=['sleeper']) for pid in ids]
now=datetime.now(timezone.utc);r.update(updated_at=now.isoformat(),reviewed_at='2026-09-28',valid_until=(now+timedelta(hours=24)).isoformat(),expires_after='2026-09-29',week=c['nfl_week'],season=c['season'],scope='Monday Week 3 decisions and early Week 4 waiver preparation. Locked scores preserved; final Monday inactives pending. No roster changes submitted.',changes=['MSU: empty TE slot after Fannin trade; conditional Ertz rental and Jones QB cover.','Netanyahu: prospective Allen-for-Badie claim; retain Kamara after Etienne injury.','Jacked Pine: keep Monday starters; retain Johnson and retire Etienne FLEX advice.','All teams and transactions reviewed; no defensible new trade offer today.'])
Path('work/research-2026-09-28.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
