import json
from pathlib import Path
from datetime import datetime,timezone,timedelta
s=json.load(open('work/daily-run/snapshot.json'));c=s['context'];r=json.load(open('outputs/daily-edition.json'))['research']
r['sources']={
'sleeper':dict(title='Sleeper current Week 4 ownership and transactions',url='https://docs.sleeper.com/',date='2026-09-29',kind='Live league data',finding='Current roster, all opposing teams, starting slots and recent trades checked. Provider injury labels are provisional.'),
'waiver':dict(title='Week 4 waiver analysis',url='https://sports.yahoo.com/fantasy/article/fantasy-football-waiver-wire-week-4-braelon-allen-kenyon-sadiq-among-top-pickups-to-target-170104704.html',date='2026-09-28; checked 2026-09-29',kind='Analyst advice',finding='Allen is an injury-contingent waiver target following Hall’s quad injury; the length of Hall’s absence is not established.'),
'kamara':dict(title='Week 4 waiver and backfield outlook',url='https://www.si.com/fantasy/week-4-waiver-wire-targets',date='2026-09-28; checked 2026-09-29',kind='Analyst advice',finding='Kamara and Kendre Miller could share work if Etienne misses Week 4. This is a conditional role outlook, not a guaranteed workload.'),
'ranks':dict(title='Early Week 4 tight-end rankings',url='https://staging-aws.sports.yahoo.com/articles/fantasy-football-te-rankings-week-000242672.html',date='2026-09-29',kind='Early analyst rankings',finding='The available ranking summary puts McBride first, Johnson and Kraft in the top ten, and Fannin in the top twelve. Full article retrieval failed; no exact ranks beyond the summary are asserted.'),
'schedule':dict(title='Week 4 schedule',url='https://www.nfl-schedule.com/weeks/week-4',date='Checked 2026-09-29',kind='Schedule',finding='Pittsburgh–Cleveland opens Thursday Oct 1. Colts–Washington is early Sunday in London; Atlanta–New Orleans is Monday Oct 5. All 32 teams are listed, with no Week 4 byes.'),
'baker':dict(title='Mayfield thumb injury',url='https://amp.nfl.com/news/buccaneers-qb-baker-mayfield-thumb-out-at-least-three-weeks-jalon-daniels',date='2026-09-28; checked 2026-09-29',kind='NFL injury report',finding='Mayfield is expected to miss at least three weeks. The MSU trade moved him away; Jacked Pine still owns him.'),
'valuation':dict(title='Trade valuation reference — stale baseline',url='https://www.fantasypros.com/2026/09/fantasy-football-trade-value-chart-week-3-2026/',date='2026-09-22; checked 2026-09-29',kind='Older analyst valuation',finding='This chart predates Week 3 injuries. A verified updated Week 4 chart was not found; do not use its numbers to price a new offer.'),
}
def m(action,pid,title,reason,cost,sources,confidence='Conditional',drop=None):
 return dict(action=action,id=pid,title=title,reason=reason,cost=cost,sources=sources,confidence=confidence,drop_id=drop)
for l in c['leagues']:
 a=r['leagues'][l['id']];t=next(t for t in l['tracking']['teams'] if c['user_id'] in [x['id'] for x in t['members']]);ps={p['id']:p for p in t['players']};starters=t['starters'][:]
 a.update(roster_ids=sorted(p['id'] for p in l['roster']),scoring_baseline=l['scoring'],slots_baseline=l['slots'],trades=[])
 if l['name']=='Jacked Pine':
  moves=[m('Hold','8183','Keep Purdy and Hurts as your QB pair','Both occupy the correct starting slots; Mayfield and Daniels are currently unavailable depth.','Six-point passing TDs support preserving active Superflex quarterbacks. No third-QB claim is urgent.',['sleeper','baker'],'Strong'),m('Hold','7002','Keep both Johnson and Kraft; revisit the TE choice','Both appear in the early top-ten TE group. There is not enough verified current ranking detail to force a swap today.','Keep Kraft provisionally; Johnson plays Monday, so check his final status before committing past Kraft’s Sunday kickoff.',['ranks','schedule'],'Hold'),m('Monitor','7543','Keep Etienne benched pending practice news','The live roster marks him Out; the Saints backfield outlook has changed.','Do not reuse last week’s start advice. Hold rather than sell at an unverified injury discount; Warren/Pollard provide cover.',['sleeper','kamara'],'Strong'),m('Monitor','12185','Have a kicker replacement plan for Shrader','The current roster flags him Questionable, and Indianapolis plays early Sunday.','Wait for the final designation; if unavailable, replace him one-for-one with a confirmed active, unrostered kicker before London kickoff. No specific claim is recommended yet.',['sleeper','schedule'])]
  headline='Keep the QB pair; monitor Etienne and the early kicker deadline.';strategy='Warren and Mayfield are already owned, Stevenson is gone, and Coleman is in reserve. Allen is unrostered, but no cut of established depth is justified before Hall news. No Week 4 game has started.';watch=['Spencer Shrader','Travis Etienne','Juwan Johnson'];score='PPR, six-point passing TDs and −2 interceptions. Keep Purdy/Hurts; no byes this week require a replacement.'
  tn='No trade proposed. Every rival has multiple quarterbacks or strong TE alternatives, limiting a depth-for-starter pitch. Injured Etienne/Mayfield are poor pieces to price with last week’s chart. Keep cover rather than force a consolidation.'
 elif l['name']=='Netanyahu Ball':
  moves=[m('Add','11576','Claim Allen for Badie if Hall’s news supports it','Allen is still unrostered in this league and has a clearer injury-contingent opportunity.','Drop Badie one-for-one if the claim clears. Avoid an all-in bid before Hall’s status is known; waiver priority and budget were not established.',['waiver','sleeper'],'Conditional','8208'),m('Hold','4035','Keep Kamara while the Saints role settles','Etienne’s injury creates an opportunity, but Miller may share the work.','Hold as depth; compare with your FLEX players after practice reports. Monday timing makes an unconfirmed Kamara start risky without a later replacement.',['kamara','schedule'],'Hold'),m('Hold','8130','Keep McBride at TE','The early ranking summary keeps McBride first. Bowers is already in FLEX; no extra TE is needed.','Do not pay for a redundant TE or drop Bowers after a single week. Standard PPR here has no TE premium.',['ranks','sleeper'],'Strong'),m('Monitor','12514','Reassess Egbuka with Tampa Bay’s QB change','Mayfield’s injury changes the passing-game context; that creates uncertainty, not an automatic bench decision.','Leave the current WR/FLEX arrangement provisional until updated projections and practice reports are available. Preserve Thomas as an alternative.',['baker','sleeper'])]
  headline='Allen-for-Badie is the waiver priority; keep Kamara and McBride.';strategy='Odunze is now in FLEX and Thomas is on the bench. MagicMax5 owns Johnson and Coker after the Warren/Tucker trade; those old trade fits are retired. Collins remains in reserve.';watch=['Braelon Allen','Alvin Kamara','Emeka Egbuka'];score='PPR, four-point passing TDs and yardage bonuses. Allen is a conditional depth addition; keep Mahomes and avoid another TE acquisition.'
  tn='No trade proposed. MagicMax5 already has Kittle/Johnson/Waller and Maye Cook has Warren/Fannin. Neither is an obvious buyer for your TE depth. Kamara’s changing role argues for waiting instead of using pre-injury prices.'
 else:
  moves=[m('Start','6797','Keep newly acquired Herbert starting','Your completed trade sent Mayfield and DJ Moore for Herbert and McLaurin. The QB emergency is resolved on the current roster.','No Jones claim needed just to fill QB. Keep Williams as conditional recovery cover; do not assume he is cleared.',['sleeper'],'Strong'),m('Start','12506','Keep Fannin at TE before Thursday’s lock','Fannin now fills the TE slot, and the early ranking summary puts him in the top twelve.','No Ertz rental is needed. Verify the final Cleveland report before Thursday 8:15 p.m. ET; avoid adding a second TE without a new need.',['ranks','schedule','sleeper'],'Lean'),m('Hold','5927','Keep McLaurin in your provisional starting WR group','He is now owned and starting alongside Lamb; advice involving DJ Moore is obsolete.','No immediate follow-up trade. Review the Washington QB and final injury reports before the early London kickoff.',['sleeper','schedule'],'Hold'),m('Hold','6806','Preserve Dobbins and receiver cover','The roster has room, and the two completed trades changed your depth. Dobbins, Emanuel Wilson and Washington provide alternatives.','Allen and Johnson are owned by other managers here. Do not chase a national waiver list by surrendering a starter; revisit FLEX after current-week usage and injury reports.',['sleeper'],'Hold')]
  headline='Herbert and McLaurin are in; Fannin’s Thursday deadline comes first.';strategy='Retired Jones and Ertz emergency recommendations after the Herbert/McLaurin and Fannin trades. The TE slot is filled, and no immediate acquisition is required.';watch=['Harold Fannin','Caleb Williams','J.K. Dobbins'];score='PPR, completion bonuses and enhanced passing-yard scoring. Herbert fills the active-QB need; recommendations remain provisional before practice reports.'
  tn='No further trade proposed. giannispetrizzo now holds Mayfield/Moore and still has Lawrence, while Diddy’s Basement owns Helm/Marks after sending Fannin. Both completed deals solve your immediate needs; preserve depth rather than paying again. No Week 4 bye creates urgency.'
 a.update(headline=headline,strategy=strategy,watch=watch,scoring_note=score,player_moves=moves)
 a['calls']=[dict(kind=x['action'],title=x['title'],reason=x['reason'],confidence=x['confidence'],sources=x['sources'],recheck=x['cost']) for x in moves]
 a['lineup']=[dict(slot=slot,id=pid,name=ps[pid]['name'],position=ps[pid]['position'],team=ps[pid].get('team'),note='Week 4 provisional: verify practice, final active status and kickoff deadline') for slot,pid in zip(t['slots'],starters)]
 a['lineup_notes']=[dict(title=x['title'],body=x['reason']+' '+x['cost'],sources=x['sources']) for x in moves]+[dict(title='Trade review',body=tn,sources=['sleeper','valuation']),dict(title='Week 4 timing',body='No games or byes yet this week. Cleveland/Pittsburgh lock Thursday; Colts/Washington lock early Sunday; Saints/Falcons play Monday. Final active lists are not available this early. The lineup retains current starters pending stronger start/sit evidence.',sources=['schedule'])]
r['candidates']=[dict(name=n,role='League-specific waiver watch; not an automatic claim',sources=['sleeper']) for n in ['Braelon Allen','Daniel Jones','Juwan Johnson','Harold Fannin']]
now=datetime.now(timezone.utc);r.update(updated_at=now.isoformat(),reviewed_at='2026-09-29',valid_until=(now+timedelta(hours=24)).isoformat(),expires_after='2026-10-06',week=c['nfl_week'],season=c['season'],scope='Week 4 early-week research. Fresh all-team ownership, trades, injury context and early analyst summaries. Lineups provisional; no transactions submitted.',changes=['MSU trade: Herbert/McLaurin in, Mayfield/Moore out; Fannin now starting.','Removed obsolete Ertz/Jones emergency claims and Monday Week 3 instructions.','Netanyahu: conditional Allen-for-Badie claim remains available; hold Kamara.','Jacked Pine: retain QBs and TE choices; monitor Etienne and Shrader.','No verified updated Week 4 trade chart found; no priced trade offer forced.'])
Path('work/research-2026-09-29.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
