import json
from pathlib import Path
from datetime import datetime,timezone,timedelta
s=json.load(open('work/daily-run/snapshot.json')); c=s['context'];r=json.load(open('outputs/daily-edition.json'))['research']
r['sources']={}
def src(k,title,url,finding,date='2026-09-25',kind='Research'):
 r['sources'][k]=dict(title=title,url=url,date=date,kind=kind,finding=finding)
src('sleeper','Sleeper current rosters and transactions','https://docs.sleeper.com/','All leagues refreshed; ownership and starting slots checked across every team. Status flags are not medical clearance.',kind='Live league data')
src('denver','Broncos final injury report','https://www.denverbroncos.com/news/injury-report-rbs-rj-harvey-and-j-k-dobbins-not-assigned-game-statuses-rb-jonah-coleman-ruled-out-for-week-3-game-vs-rams','Coleman is out with an ankle injury. Dobbins and Harvey have no game designation; both practiced fully Friday.',kind='Official team report')
src('bowers','NFL: Bowers questionable','https://fantasy-www.nfl.com/news/raiders-tight-end-brock-bowers-is-questionable-to-play-vs-saints','Bowers remains questionable with a knee injury after missing the opening two games.',kind='NFL injury report')
src('grades','FantasyPros Week 3 grades','https://www.fantasypros.com/2026/09/fantasy-football-week-3-player-grades-start-sit-advice-2026/','Etienne is ahead of Pollard on the running-back board. Badie and Helm rank low at their positions. These are analyst opinions, not custom-scoring projections.')
src('te','NBC Week 3 tight-end rankings','https://www.nbcsports.com/fantasy/football/news/week-3-fantasy-football-rankings-te-k-def','McBride TE1; Bowers TE3; Helm TE30.',date='2026-09-24')
src('moore','DJ Moore returns to practice','https://www.fantasypros.com/nfl/news/610554/dj-moore-shoulder-back-practice-friday.php','Moore returned Friday following a shoulder issue. Practice participation does not establish final game availability.')
src('price','Jadarian Price practice update','https://ca.sports.yahoo.com/news/limited-practice-jadarian-price-012545607.html','Price was limited Thursday. Wilson remains a contingent option; Friday status and Sunday inactives must be checked.')
src('trade','FantasyPros Week 3 trade values','https://www.fantasypros.com/2026/09/fantasy-football-trade-value-chart-week-3-2026/','Rest-of-season values are a negotiation baseline, not acceptance probabilities or exact values for custom scoring.',date='2026-09-22; checked 2026-09-25')
src('schedule','NFL Week 3 schedule and injuries','https://amp.nfl.com/news/nfl-week-3-injury-report-player-statuses-for-all-16-games','Atlanta at Green Bay was Thursday September 24. Those players are already locked; Sunday and Monday final inactives are pending.',date='2026-09-23; checked 2026-09-25')
def move(action,pid,title,reason,cost,ss,confidence='Conditional'):
 return dict(action=action,id=pid,title=title,reason=reason,cost=cost,sources=ss,confidence=confidence,drop_id=None)
for l in c['leagues']:
 a=r['leagues'][l['id']];t=next(t for t in l['tracking']['teams'] if c['user_id'] in [m['id'] for m in t['members']]);ps={p['id']:p for p in t['players']};starters=t['starters'][:]
 a.update(roster_ids=sorted(p['id'] for p in l['roster']),scoring_baseline=l['scoring'],slots_baseline=l['slots'],trades=[])
 if l['name']=='Jacked Pine':
  moves=[move('Start','7543','Lean Etienne over Pollard in FLEX','Current positional grades put Etienne ahead; this is a modest PPR lineup lean, not a certainty.','No transaction; retain Pollard as RB cover.',['grades'],'Lean'),move('Hold','8183','Keep Purdy and Hurts starting','Your quarterback correction is complete; Daniels remains Out in the fresh snapshot.','Six-point passing TDs make active QB depth valuable in Superflex. Do not trade Purdy away to fill a minor hole.',['sleeper'],'Strong'),move('Sit','13345','Keep Coleman on the bench','Denver has ruled him out, while Dobbins and Harvey return.','No immediate claim required with your existing RB depth. Do not follow the earlier Coleman start contingency.',['denver'],'Strong'),move('Hold','9484','Keep Kraft in his locked slot','Green Bay played Thursday and Kraft is already your starting TE.','No retroactive swap to Johnson; use remaining unlocked slots only.',['schedule','sleeper'],'Strong')]
  starters=['7543' if p=='5967' else p for p in starters]
  headline='Etienne gets the FLEX lean; your QB correction is complete.'
  strategy='Bigsby is no longer on your roster. Keep Coleman benched and preserve both active quarterbacks. Christopher now holds Kittle and Hubbard after the Parker Washington trade; previous partner fits have changed.'
  tn='No offer recommended. Christopher has multiple quarterbacks; nicbarbz40 also added Nix. Your active Superflex quarterbacks are needed, and depth-only offers do not clearly improve another team’s starters. Keep RB and bye cover.'
  watch=['Jonah Coleman','Saquon Barkley'];scoring='PPR and six-point passing TDs. Etienne over Pollard is a modest analyst lean; Kraft is locked after Thursday.'
 elif l['name']=='Netanyahu Ball':
  moves=[move('Monitor','11604','Bowers can stay in FLEX only if cleared','His status improved from Out to Questionable, but he is not confirmed active.','If inactive or limited, use an unlocked alternative such as Odunze; decide before the earlier kickoff.',['bowers','sleeper']),move('Sit','13345','Retire the Coleman FLEX recommendation','Coleman is officially out. Your current FLEX now uses Brian Thomas instead.','Keep Coleman benched; Badie is not an automatic substitute with both Denver veterans cleared.',['denver','sleeper'],'Strong'),move('Hold','8130','Keep McBride at TE','He remains the top option on the checked TE board.','No need to trade for another TE; hold Goedert on the bench while Doubtful.',['te','sleeper'],'Strong'),move('Hold','8208','Treat Badie as depth, not a starter','Dobbins and Harvey are cleared, limiting the injury-replacement case for Badie.','Avoid additional waiver spending on this backfield; keep current starters and reassess his bench value after role evidence.',['denver','grades'],'Hold')]
  headline='Bowers needs a Sunday check; Coleman must stay benched.'
  strategy='Collins is now in reserve and Brian Thomas is starting. The prior two-Out-FLEX warning is obsolete. Keep an unlocked replacement ready for Bowers; preserve RB depth after the completed trade.'
  tn='No trade offer recommended. MagicMax5 has Warren, Kittle and Waller already; another tight end is a weak fit. Kyle’s Clash Team just added Terrance Ferguson. Do not sell an injured Bowers merely to clear a slot while his return is unsettled.'
  watch=['Brock Bowers','Dallas Goedert','Jonah Coleman'];scoring='PPR, four-point passing TDs and yardage bonuses; no TE premium. Bowers FLEX is conditional on availability and workload.'
 else:
  moves=[move('Hold','12502','Use Helm provisionally; Loveland is no longer available','Your Loveland claim failed and giannispetrizzo acquired him. Ertz is already gone and Helm is your current TE.','Do not repeat the stale Loveland add/drop. Mayer is free but is not a clear upgrade with Bowers possibly returning.',['sleeper','bowers'],'Hold'),move('Monitor','4983','Keep a replacement ready for Moore','He returned to practice Friday, but your live roster still marks him Questionable.','If unavailable, move Michael Wilson from FLEX to WR and use a cleared RB in FLEX, or use Malik Washington. Check kickoff order first.',['moore','sleeper']),move('Hold','6806','Dobbins is available again, but the backfield is shared','Denver removed his designation; Harvey is also returning.','Retain Dobbins as RB/FLEX cover. Availability alone does not guarantee a workload upgrade over your current starters.',['denver'],'Hold'),move('Monitor','11435','Wilson remains dependent on Price’s status','Thursday limitations keep the contingency alive, but do not establish that Price will miss Sunday.','Bench Wilson provisionally; reassess final reports before using him over Michael Wilson. Keep Mayfield starting while Williams is Doubtful.',['price','sleeper'])]
  headline='Loveland was claimed elsewhere; monitor Moore and your RB cover.'
  strategy='Keep Helm provisionally after the completed Ertz swap. Dobbins is cleared; Wilson still depends on Seattle’s backfield health. Your starting QB is already Mayfield.'
  tn='No offer recommended. Teams with extra tight ends were reviewed, but your roster needs its WR injury cover and RB depth. giannispetrizzo just spent a claim on Loveland and has Goedert Doubtful, reducing incentive to move Loveland cheaply. Revisit a TE trade after Sunday roles settle; no bye-driven urgency was established.'
  watch=['DJ Moore','J.K. Dobbins','Emanuel Wilson','Gunnar Helm'];scoring='PPR plus 0.1 per completion and one passing-yard point per 22.5 yards. Keep Mayfield; preserve an eligible WR replacement for Moore.'
 a.update(headline=headline,strategy=strategy,watch=watch,scoring_note=scoring,player_moves=moves)
 a['calls']=[dict(kind=x['action'],title=x['title'],reason=x['reason'],confidence=x['confidence'],sources=x['sources'],recheck=x['cost']) for x in moves]
 a['lineup']=[dict(slot=slot,id=pid,name=ps[pid]['name'],position=ps[pid]['position'],team=ps[pid].get('team'),note='Locked after Thursday' if ps[pid].get('team') in ['GB','ATL'] else 'Provisional; verify final availability and kickoff order') for slot,pid in zip(t['slots'],starters)]
 a['lineup_notes']=[dict(title=x['title'],body=x['reason']+' '+x['cost'],sources=x['sources']) for x in moves]+[dict(title='Trade review',body=tn,sources=['sleeper','trade']),dict(title='Game locks',body='Atlanta and Green Bay have already played. Do not move locked players. Remaining lineups require final inactive checks; no transactions were submitted.',sources=['schedule'])]
r['candidates']=[dict(name=n,role='Monitor availability and role; not an automatic claim',sources=['sleeper']) for n in ['Michael Mayer','Colston Loveland','Jonah Coleman','Emanuel Wilson']]
now=datetime.now(timezone.utc);r.update(updated_at=now.isoformat(),reviewed_at='2026-09-25',valid_until=(now+timedelta(hours=24)).isoformat(),expires_after='2026-09-29',week=c['nfl_week'],season=c['season'],scope='September 25 live ownership and current injury research across all leagues. Remaining lineups provisional; no roster actions submitted.',changes=['Jacked Pine: Etienne FLEX lean; Purdy/Hurts already starting; Kraft locked.','Netanyahu Ball: Coleman out, Bowers questionable, Badie loses injury-replacement appeal.','MSU: Loveland acquired by another manager; Helm replaces Ertz; Moore needs final status check.','Dobbins cleared; no supported new trade or waiver claim after roster review.'])
Path('work/research-2026-09-25.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
