import json
from pathlib import Path
from datetime import datetime,timezone,timedelta
s=json.load(open('work/daily-run/snapshot.json'));c=s['context'];r=json.load(open('outputs/daily-edition.json'))['research'];P=json.load(open('work/daily-cache/players.json'))
r['sources']={}
def source(k,title,url,date,kind,finding):r['sources'][k]=dict(title=title,url=url,date=date,kind=kind,finding=finding)
source('sleeper','Sleeper live league snapshot','https://docs.sleeper.com/','Sep 23, 2026','Live ownership and rules','Current ownership, reserves, starters, transactions and scoring refreshed for all three leagues. Injury flags are provider labels, not final medical clearance.')
source('ranks','FantasyPros · Week 3 expert rankings','https://www.fantasypros.com/2026/09/fantasy-football-rankings-most-accurate-experts-week-3-2026/','Sep 23, 2026','Analyst rankings','McBride leads the TE list; Loveland is TE12. McConkey ranks ahead of Stevenson on the flex board. Weekly opinions are not projections under custom rules.')
source('usage','Fantasy Life · Week 3 running back upgrades','https://www.fantasylife.com/articles/fantasy/upgrades-for-week-3-running-back-rankings','Sep 23, 2026','Usage and matchup analysis','Coleman benefited from Denver injuries, with 10 carries and three targets in Week 2. Emanuel Wilson had 21 carries after Price exited. Both roles depend on injured teammates returning.')
source('trade','FantasyPros · Week 3 trade values','https://www.fantasypros.com/2026/09/fantasy-football-trade-value-chart-week-3-2026/amp/','Sep 22, checked Sep 23, 2026','Rest-of-season analyst valuation','Values distinguish Superflex from single-QB and ordinary PPR from TE premium. Loveland retains meaningful rest-of-season value. Values do not imply trade acceptance.')
source('ertz','Eagles · Zach Ertz signing','https://www.philadelphiaeagles.com/news/eagles-sign-zach-ertz-super-bowl-lii-champion-three-time-pro-bowl-tight-end','Sep 22, 2026','Official team report','Philadelphia confirms Ertz has signed after recovering from a knee injury. The announcement does not establish a Week 3 workload.')
source('barkley','Eagles · Week 2 takeaways','https://www.philadelphiaeagles.com/news/eagles-6-takeaways-from-an-incredible-come-from-behind-win-over-the-titans-jalen-hurts-devonta-smith-2026-nfl-week-2','Sep 20, checked Sep 23, 2026','Official team report','Barkley was limited by a stinger. Monitor later practice reports and final status; Bigsby is now on your Jacked Pine roster.')
source('bears','Bears · Williams week-to-week','https://www.chicagobears.com/news/caleb-williams-week-to-week-with-hamstring-injury','Sep 21, checked Sep 23, 2026','Official team report','Williams is week-to-week with a hamstring injury and not expected to practice. This also introduces uncertainty for Odunze and Loveland.')
source('daniels','Commanders · latest on Daniels','https://www.commanders.com/news/jayden-daniels-dan-quinn-commanders','Sep 21, checked Sep 23, 2026','Official team report','Daniels suffered a dislocated elbow; Washington identifies Mariota as the current starter pending further review.')
source('schedule','Sharp Football · Week 3 schedule and rankings','https://www.sharpfootballanalysis.com/fantasy/fantasy-football-rankings-weekly/','Sep 23, 2026','Weekly schedule','Atlanta–Green Bay opens Thursday; Philadelphia–Chicago plays Monday. Preserve later-slot flexibility and check final inactives before each kickoff.')
# Extend market from the same fresh all-team ownership snapshot and daily player metadata.
for l in c['leagues']:
 owners={p['id']:t['name'] for t in l['tracking']['teams'] for p in t['players']}
 for pid in ['12517','13345','11435','13346']:
  if not any(p['id']==pid for p in l['market']):
   p=P[pid];l['market'].append(dict(id=pid,name=p['full_name'],position=p['position'],team=p.get('team'),injury=p.get('injury_status'),owner=owners.get(pid)))
Path('work/daily-run/snapshot.json').write_text(json.dumps(s,ensure_ascii=False))
r['candidates']=[dict(name=P[pid]['full_name'],role='Ownership and role watch',sources=['sleeper']) for pid in ['12517','13345','11435','13346','13296','9482']]
def m(action,pid,title,reason,cost,src,confidence='Lean',drop=None):return dict(action=action,id=pid,title=title,reason=reason,cost=cost,sources=src,confidence=confidence,drop_id=drop)
for l in c['leagues']:
 a=r['leagues'][l['id']];t=next(t for t in l['tracking']['teams'] if c['user_id'] in [m['id'] for m in t['members']]);ps={p['id']:p for p in t['players']};starters=list(t['starters']);a.update(roster_ids=sorted(p['id'] for p in l['roster']),scoring_baseline=l['scoring'],slots_baseline=l['slots'],trades=[])
 if l['name']=='Jacked Pine':
  moves=[m('Start','8183','Move Purdy into Superflex','Daniels remains in your starting slot despite an Out flag and the official elbow update.','No acquisition cost; retain Daniels on the bench. Six-point passing TDs favor using your active quarterback.',['daniels','sleeper'],'Strong'),m('Start','11635','Lean McConkey over Stevenson in FLEX','The current flex board prefers McConkey; he gives another receiving route to PPR points.','Stevenson moves to the bench, preserving RB cover. Recheck final availability.',['ranks'],'Lean'),m('Hold','9225','Keep Bigsby as Barkley cover','Barkley’s stinger limited him last game; Bigsby is already yours.','A bench slot buys a Monday contingency. Do not start Bigsby merely because Barkley is Questionable.',['barkley','sleeper'],'Hold'),m('Hold','13345','Keep Coleman; monitor Denver’s backfield','His Week 2 opportunity came with Dobbins and Harvey injured.','Hold the newly acquired player; do not spend another claim or trade him before role clarity.',['usage'],'Hold')]
  starters=[('8183' if p=='11566' else '11635' if p=='7611' else p) for p in starters]
  a.update(headline='Purdy into Superflex; McConkey gets the FLEX lean.',strategy='Reed and Lloyd are gone; Coleman and Bigsby are owned. Keep your QB cover while Daniels is out. Jordan Love is now owned by Christopher, so the old free-agent alternative is retired.',watch=['Saquon Barkley','Jonah Coleman','Jayden Daniels'],scoring_note='PPR, six-point passing TDs and −2 interceptions. Purdy is preferable to a skill player in Superflex; keep Bigsby available for Philadelphia’s Monday game.')
  trade_note='No trade recommended: Purdy is now needed as a starter. The other teams’ replacement QBs and your six-team waiver alternatives make a depth-for-starter offer difficult to justify.'
 elif l['name']=='Netanyahu Ball':
  moves=[m('Start','11620','Use Odunze in FLEX for an Out player','Both Bowers and Collins occupy FLEX slots with Out flags. Odunze is a rostered alternative.','No claim cost. Chicago’s quarterback injury lowers confidence; reassess if either injured star is officially cleared.',['sleeper','bears'],'Strong'),m('Start','13345','Use Coleman in the other FLEX provisionally','He is available on your bench and offers a current alternative to a player listed Out.','Role depends on Dobbins and Harvey. If Denver’s backfield returns, compare Black and other cleared players before Sunday night.',['usage','sleeper'],'Conditional'),m('Start','8130','Keep McBride at tight end','McBride arrived in the completed trade and is the leading tight end on the checked weekly board.','Bench Goedert while Questionable; do not acquire a fourth TE.',['ranks','sleeper'],'Strong'),m('Hold','11584','Keep Irving as RB2','Irving is now owned; the current running-back list supports a starting role against Minnesota.','Your trade cost Hall and Swift, so protect remaining RB depth instead of immediately making another deal.',['usage','sleeper'],'Hold')]
  starters=[('11620' if p=='11604' else '13345' if p=='7569' else p) for p in starters]
  a.update(headline='Replace both Out FLEX starters after the trade.',strategy='Irving, Odunze and McBride are now yours. Retire advice involving Hall, Swift and Golden. McBride resolves the urgent TE need; keep Bowers and Collins on the bench pending updated status.',watch=['Jonah Coleman','Nico Collins','Brock Bowers','Dallas Goedert'],scoring_note='PPR with four-point passing TDs and yardage bonuses. Keep Mahomes; use active skill players in both FLEX slots. No TE premium supports an automatic second TE start.')
  trade_note='No new trade recommended today. McBride fills TE; Bowers and Goedert have health uncertainty. Your partner MagicMax5 already has multiple tight ends and now owns Hall/Swift/Golden, changing the previous fit.'
 else:
  moves=[m('Add','12517','Reclaim Loveland; drop Ertz','Fresh all-team ownership shows Loveland unowned after your drop. Ertz’s signing does not establish a Week 3 role; Loveland remains ranked TE12.','Use a waiver claim if required, dropping Ertz one-for-one. Chicago’s QB injury remains a risk; no FAAB amount is asserted.',['ranks','ertz','trade','sleeper'],'Lean','1339'),m('Hold','4892','Keep Mayfield starting','The previous QB change is complete; Williams remains Out with the Bears describing a week-to-week hamstring injury.','No further transaction. This league rewards completions and passing yards, but those bonuses do not make an unavailable QB usable.',['bears','sleeper'],'Strong'),m('Monitor','11435','Wilson can enter FLEX if Price remains limited','Wilson’s expanded Week 2 workload makes him a candidate over Michael Wilson if the Seattle backfield remains depleted.','Keep Michael Wilson in the provisional lineup until the role is confirmed. Do not treat a one-week workload as guaranteed.',['usage'],'Conditional'),m('Monitor','6806','Wait on Dobbins before starting him','Dobbins is Questionable after a reported hamstring exit; Coleman’s opportunity depends on the same situation.','Hold on the bench for now. A healthy return could alter both this league and your Coleman lineups elsewhere.',['usage','sleeper'],'Monitor')]
  a.update(headline='Reclaim Loveland rather than relying only on Ertz.',strategy='Mayfield and Malik Washington are already starting. Douglas and Loveland were dropped for Emanuel Wilson and Ertz. Loveland is available again; Braelon Allen is now owned by ashwind109 and Mayer by Bo Dix.',watch=['Colston Loveland','Emanuel Wilson','J.K. Dobbins','Zach Ertz'],scoring_note='PPR, four-point passing TDs, 0.1 per completion and one passing-yard point per 22.5 yards, plus bonuses. The QB change is complete; tight-end availability is now the main concern.')
  trade_note='No trade recommended: reclaiming an available tight end costs one roster spot rather than a player sent to another manager. Keep RB depth with Dobbins uncertain; do not trade Mayfield while Williams is unavailable.'
 a['player_moves']=moves;a['calls']=[dict(kind=x['action'],title=x['title'],reason=x['reason'],confidence=x['confidence'],sources=x['sources'],recheck=x['cost']) for x in moves]
 a['lineup']=[dict(slot=slot,id=pid,name=ps[pid]['name'],position=ps[pid]['position'],team=ps[pid].get('team'),note=('Conditional only: replace with Loveland after a successful claim; verify Ertz is active' if pid=='1339' else 'Provisional: check final injury status and role before kickoff')) for slot,pid in zip(t['slots'],starters)]
 a['lineup_notes']=[dict(title=x['title'],body=x['reason']+' '+x['cost'],sources=x['sources']) for x in moves]+[dict(title='Trade review',body=trade_note,sources=['trade','sleeper']),dict(title='Week 3 locks',body='Green Bay and Atlanta play Thursday. Philadelphia and Chicago play Monday. No Week 3 game has kicked off at this review; final inactive lists are not yet available. Preserve late alternatives.',sources=['schedule'])]
now=datetime.now(timezone.utc);r.update(updated_at=now.isoformat(),reviewed_at='2026-09-23',valid_until=(now+timedelta(hours=24)).isoformat(),expires_after='2026-09-29',week=c['nfl_week'],season=c['season'],scope='Fresh ownership and dated Week 3 analysis. Lineups are provisional pending final injury reports. No roster moves or offers were submitted.',changes=['Updated all three leagues after completed claims and the Irving–Odunze–McBride trade.','Jacked Pine: Purdy for Daniels; McConkey FLEX lean; keep Bigsby as Monday cover.','Netanyahu Ball: Odunze and Coleman provisionally replace Out FLEX players; McBride stays at TE.','MSU: reclaim available Loveland for Ertz; preserve Mayfield and monitor Wilson/Dobbins.','Retired stale targets and trade ideas; no supported new trade today.'])
Path('work/research-2026-09-23.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
