from pathlib import Path
import json
root=Path('outputs/Sleeper Brief.app/Contents/Resources')
p=root/'index.html';s=p.read_text()
logo='<svg viewBox="0 0 40 28" aria-hidden="true"><path d="M6 12 10 3h6l2 10m4 0 2-10h6l4 9M16 9h8" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><circle cx="11" cy="18" r="8"/><circle cx="29" cy="18" r="8"/><circle cx="11" cy="18" r="4" fill="#17352c"/><circle cx="29" cy="18" r="4" fill="#17352c"/></svg>'
s=s.replace('<title>Sleeper Brief</title>','<title>Binocular</title>')
s=s.replace('<div class="brand"><div class="logo">s</div>sleeper <small>brief</small></div>','<div class="brand"><div class="logo">'+logo+'</div>binocular</div><div class="brand-caption">FOOTBALL SCOUTING DESK</div>')
s=s.replace('Your weekly edge.<br>Personal companion · Unofficial','Read the field.<br>Independent Sleeper companion')
s=s.replace('Ahead of the game.','Your weekly game plan.')
s=s.replace('<div class="top-actions">','<div class="top-actions"><button class="action" onclick="toggleSidebar()" aria-label="Toggle league sidebar" title="Toggle sidebar (Control–Command–S)">◧</button>')
s=s.replace('<div id="content"></div>','<div id="freshness"></div><div class="view-switch" role="group" aria-label="Report view"><button id="overview-view" onclick="setView(\'overview\')">Game plan <kbd>⌘1</kbd></button><button id="research-view" onclick="setView(\'research\')">Scouting report <kbd>⌘2</kbd></button></div><div id="content"></div>')
s=s.replace('Trending adds are a signal, not a player ranking. Trade fit is based on roster depth.<br>For start/sit advice, copy your brief into your preferred AI assistant.','League data and trending adds: <a href="https://docs.sleeper.com/">Sleeper</a>. Scouting calls are dated analyst judgments, not automatic lineup changes.')
s=s.replace('</style></head>','</style><link rel="stylesheet" href="binocular.css"></head>')
s=s.replace('<script>\nlet leagues=','<script src="research.js"></script><script>\nlet leagues=')
s=s.replace("/^- (.+) — added in ([\\d,]+) leagues \\(24h\\)/","/^- (.+) — (?:added in )?([\\d,]+) (?:leagues|adds) \\(24h\\)/")
s=s.replace("issues.some(s=>s.includes('No red flags'))","issues.some(s=>s.includes('No red flags')||s.includes('No flagged injuries'))")
s=s.replace("card('Trade angles','POSITIONAL DEPTH'","card('Roster balance','COUNTS ONLY'")
s=s.replace("card('Your roster',roster.length+' players'","card('Current roster',roster.length+' players'")
s=s.replace('>Starting lineup</button>','>Starters</button>')
s=s.replace("rosterTab='Bench';render()", "rosterTab='Bench';render()")
s=s.replace("+'</div>'+ (roster.map(playerRow)","+'<button class=\"tab '+(rosterTab==='Reserve'?'active':'')+'\" role=\"tab\" aria-selected=\"'+(rosterTab==='Reserve')+'\" onclick=\"rosterTab=\\'Reserve\\';render()\">Reserve</button></div>'+ (roster.map(playerRow)")
s=s.replace("card('Standings',standings.length+' teams'","card('Standings',standings.length+' teams · wins / points'")
s=s.replace('</script></body>','</script><script src="binocular.js"></script></body>')
p.write_text(s)
r=json.loads((root/'research.json').read_text());snap=json.loads(Path('work/research/snapshot.json').read_text())
for lg in snap['leagues']:
 r['leagues'][lg['id']]['roster_ids']=sorted(p['id'] for t in lg['teams'] if t['mine'] for p in t['players'])
r['leagues']['1385050179488460800']['calls'][0]['reason']=r['leagues']['1385050179488460800']['calls'][0]['reason'].replace('Two early QB lists favor Nix','The reviewed QB ranking favors Nix')
(root/'research.json').write_text(json.dumps(r,indent=2,ensure_ascii=False));(root/'research.js').write_text('window.RESEARCH = '+json.dumps(r,ensure_ascii=False)+';\n')
