// Title model view: connects Claude's simulation, trade scan and acceptance model to Binocular.
let modelData=null,modelBusy=false,modelStatus='',modelRuns={},modelK=null,modelRunId=0;
const modelButton=document.createElement('button');modelButton.id='model-view';modelButton.textContent='Title model';modelButton.onclick=()=>setView('model');document.querySelector('.view-switch').append(modelButton);
const mEsc=v=>esc(String(v??''));const mPct=x=>(100*x).toFixed(1)+'%';
const receiveBeforeModel=window.receiveDesk;
window.receiveDesk=data=>{if(data&&data.model){modelData=data.model;modelBusy=false;modelRuns={};modelStatus='Data loaded '+new Date().toLocaleTimeString()+'. Running simulations…';if(currentView==='model')mRender();setTimeout(()=>mRunLeague(mLeagueId()),30)}
 else if(data&&data.model_error){modelBusy=false;modelStatus='Model data failed: '+data.model_error;if(currentView==='model')mRender()}
 receiveBeforeModel(data)};
function mRequest(){if(modelBusy)return;if(typeof deskBusy!=='undefined'&&deskBusy){modelStatus='The desk is refreshing; try again in a moment.';mRender();return}modelBusy=true;modelStatus='Fetching projections, stats, schedules and trade history… (first run can take a minute)';mRender();window.webkit.messageHandlers.app.postMessage({action:'desk',payload:JSON.stringify({op:'model'})})}
function mLeagueId(){const name=leagues[selected]?.name;if(!modelData)return null;return Object.keys(modelData.leagues).find(id=>modelData.leagues[id].name===name)||Object.keys(modelData.leagues)[0]}
function mMarket(lid){return (typeof deskState!=='undefined'&&deskState?.markets?.[lid])||{players:{}}}
function mModels(){const out={};for(const lid in modelData.leagues)out[lid]=TitleModel.prepare(modelData,lid,mMarket(lid));return out}
function mLabels(){const extra=((typeof deskState!=='undefined'&&deskState?.offers)||[]).filter(o=>o.direction==='sent'&&['accepted','rejected'].includes(o.outcome)&&(o.give||[]).length&&(o.receive||[]).length).map(o=>({lid:o.league_id,r:o.give,g:o.receive,y:o.outcome==='accepted'?1:0}));return [...modelData.labels,...extra]}
function mChunks(fn,total,chunk,done){let n=0;const id=modelRunId;const step=()=>{if(id!==modelRunId)return;const k=Math.min(chunk,total-n);fn(k);n+=k;if(n<total)setTimeout(step,0);else done()};step()}
function mRunLeague(lid){if(!modelData||!lid)return;modelRunId++;const runId=modelRunId;const TM=TitleModel,models=mModels(),M=models[lid];modelK=TM.fitK(models,mLabels());
 const E=TM.engine(M),cands=TM.scan(M,M.L.me,{top:8,k:modelK.k});const scen=[{name:'Current roster'},...cands.map(c=>({name:'trade',c,moves:TM.movesFor(c)}))];
 const acc={},N=M.L.teams&&Object.keys(M.L.teams).length>12?6000:10000;modelRuns[lid]={M,E,cands,acc,done:false,progress:0,N};
 mChunks(k=>{TM.simulate(M,E,scen,k,acc,9);modelRuns[lid].progress=acc.res[0].n/N;if(currentView==='model'&&mLeagueId()===lid)mRenderProgress()},N,500,()=>{modelRuns[lid].done=true;modelStatus='Simulated '+N.toLocaleString()+' seasons per scenario.';if(currentView==='model'&&runId===modelRunId)mRender()})}
function mRunRivals(lid){const run=modelRuns[lid];if(!run||!run.done)return;const TM=TitleModel,M=run.M,me=M.L.me;const picks=[];for(const r in M.L.teams){if(r===me)continue;TM.scan(M,r,{top:1,perPartner:1,k:modelK.k,depth:Object.keys(M.L.teams).length>12?8:12}).forEach(c=>picks.push(c))}
 const acc={},N=Object.keys(M.L.teams).length>12?3000:6000;run.rivals={picks,acc,done:false};modelRunId++;mChunks(k=>{picks.forEach((c,i)=>{const a=acc[i]||(acc[i]={});TM.simulate(M,run.E,[{name:'x',moves:TM.movesFor(c)}],k,a,21)})},N,300,()=>{run.rivals.done=true;mRender()});mRender()}
function mRenderProgress(){const el=document.querySelector('#model-progress');const run=modelRuns[mLeagueId()];if(el&&run)el.textContent='Simulating… '+Math.round(100*run.progress)+'%'}
function mName(p){return (modelData.players[p]||[p])[0]}
function mRender(){const box=$('content');if(!modelData){box.innerHTML=`<div class="desk"><section class="desk-hero"><div class="kicker">CLAUDE TITLE MODEL</div><h2>Title odds, best trades, acceptance odds.</h2><p>Runs 10,000 simulated seasons per scenario on this Mac using Sleeper projections, 3-year history, injury risk, bye weeks and your real playoff bracket. Trade willingness is a heuristic informed by completed trades and market values, not a calibrated probability.</p><div class="desk-actions"><button onclick="mRequest()">Load model data</button></div><p role="status">${mEsc(modelStatus)}</p></section></div>`;return}
 const lid=mLeagueId(),run=modelRuns[lid];if(!run){mRunLeague(lid)}const R=modelRuns[lid];const M=R.M,me=M.L.me,acc=R.acc;
 let body=modelEvidence(M);if(!R.done){body+=`<p id="model-progress">Simulating… ${Math.round(100*R.progress)}%</p>`}else{const base=acc.res[0],n=base.n,tt=base.titles;
  const odds=Object.entries(M.L.teams).map(([r,t])=>[r,t.name,t.w+'-'+t.l,(tt[r]||0)/n]).sort((a,b)=>b[3]-a[3]);
  body+=dPanel('Title race · '+n.toLocaleString()+' simulated seasons',`<p>You: playoffs ${mPct(base.po/n)} · #1 seed ${mPct(base.s1/n)} · finals ${mPct(base.fin/n)} · <b>title ${mPct(base.title/n)}</b> · expected wins rest of season ${(base.wins/n).toFixed(1)}</p><div class="pt-row" role="list">${odds.map(([r,nm,rec,p],i)=>`<div class="pt-tile ${r===me?'me':''}" role="listitem"><span class="pt-num" aria-hidden="true">${i+1}</span><b>${mEsc(nm)}${r===me?' <span class="pt-badge">YOU</span>':''}</b><div class="pt-odds">${mPct(p)}</div><small>${mEsc(rec)} · title odds</small></div>`).join('')}</div>`);
  const ss=TitleModel.startSit(M),pv=p=>M.val[p]?M.val[p][0]:0,stLabel=p=>{const x=M.st(p);return x?' ('+x+')':''};
  const opp=w=>{const g=(M.L.sched[w]||[]).find(x=>x.includes(me));return g?M.L.teams[g[0]===me?g[1]:g[0]].name:'—'};
  const strip=M.W.slice(0,M.nReg).map((w,i)=>{const p=base.wk[i]/n;return `<div class="pt-week ${p<.45?'lo':p>=.55?'hi':''}"><small>WK ${w}</small><b>${Math.round(p*100)}%</b><span>${mEsc(opp(w))}</span></div>`}).join('');
  body+=dPanel('This week',`${ss.ins.length?`<p><b>Lineup change, projected +${(ss.bestT-ss.curT).toFixed(1)} points.</b> Start: ${ss.ins.map(p=>`<b>${mEsc(mName(p))}</b> (${pv(p).toFixed(1)})`).join(', ')}. Bench: ${ss.outs.map(p=>`${mEsc(mName(p))} (${pv(p).toFixed(1)}${mEsc(stLabel(p))})`).join(', ')||'—'}. Check kickoff locks before changing.</p>`:'<p>Your Sleeper lineup matches the model’s best lineup for this week.</p>'}<p>Win odds by week (regular season):</p><div class="pt-weeks">${strip}</div>`);
  const fa=TitleModel.faScan(M,6);
  body+=dPanel('Free agents worth a claim',fa.length?`<table class="table"><tr><td>Add</td><td>Drop</td><td>Rest of season</td><td>This week</td></tr>${fa.map(x=>`<tr><td style="white-space:nowrap"><b>${mEsc(mName(x.add))}</b> <small>${mEsc((modelData.players[x.add]||[])[1]||'')}</small></td><td>${mEsc(mName(x.drop))}</td><td>+${x.gain.toFixed(1)} pts/wk</td><td>${x.week>0?'+':''}${x.week.toFixed(1)}</td></tr>`).join('')}</table><p>Gain is to your best weekly lineup, after the cheapest drop. Waiver order and FAAB still apply.</p>`:'<p>No free agent improves your lineup right now.</p>');
  const rows=R.cands.map((c,i)=>{const s=acc.res[i+1],d=(s.title-base.title)/n;return {c,d,s1:s.s1/n,ev:c.p*d}}).filter(x=>x.d>0).sort((a,b)=>b.ev-a.ev);
  body+=dPanel('Best offers to send',`<p>Ranked by heuristic willingness × simulated title gain. Willingness is not a validated acceptance probability (${modelData.accepted.length} accepted trade sides and ${modelK.n} recorded outcomes; market weight ${modelK.k}). Verify injuries and rosters before sending.</p>${rows.length?'':'<p><b>No acceptable trade improves your title odds right now.</b> Hold, and rerun after waivers or injuries.</p>'}<table class="table" ${rows.length?'':'hidden'}><tr><td>Partner</td><td>You send → you get</td><td>Willingness score</td><td>Title</td></tr>${rows.map(x=>`<tr><td>${mEsc(M.L.teams[x.c.r].name)}</td><td>${mEsc(x.c.give.map(mName).join(' + '))} → ${mEsc(x.c.get.map(mName).join(' + '))}</td><td>${Math.round(x.c.p*100)}/100</td><td>${mPct(base.title/n)} → <b>${mPct(base.title/n+x.d)}</b></td></tr>`).join('')}</table>`);
  if(R.rivals){if(!R.rivals.done)body+=dPanel('Rival moves','<p>Simulating each manager’s best trade…</p>');else{body+=dPanel('Each rival’s best acceptable trade',`<p>What each manager’s best move would do to the title race.</p><table class="table"><tr><td>Manager</td><td>Trade</td><td>Willingness score</td><td>Their title</td><td>Your title</td></tr>${R.rivals.picks.map((c,i)=>{const a=R.rivals.acc[i].res[0],k=a.n;return `<tr><td>${mEsc(M.L.teams[c.x].name)} ↔ ${mEsc(M.L.teams[c.r].name)}</td><td>${mEsc(c.give.map(mName).join(' + '))} → ${mEsc(c.get.map(mName).join(' + '))}</td><td>${Math.round(c.p*100)}/100</td><td>${mPct((tt[c.x]||0)/n)} → ${mPct((a.titles[c.x]||0)/k)}</td><td>${mPct(base.title/n)} → ${mPct(a.title/k)}</td></tr>`}).join('')}</table>`)}}
  else body+=`<div class="desk-actions"><button onclick="mRunRivals('${lid}')">Scan every rival’s best trade</button></div>`}
 box.innerHTML=`<div class="desk"><section class="desk-hero"><div class="kicker">CLAUDE TITLE MODEL · ${mEsc(M.L.name)} · WEEK ${mEsc(modelData.week)}</div><h2>Win the league, not the week.</h2><p>Data ${mEsc(new Date(modelData.built_at).toLocaleString())}. Simulations run on this Mac. No offers are sent.</p><div class="desk-actions"><button onclick="mRequest()">Refresh model data</button></div><p role="status">${mEsc(modelStatus)}</p></section>${body}<p class="desk-foot">Method: weekly projections blended with 3-year history (weights backtested on the 2024 and 2025 seasons: 95/5 for RB, WR and TE, 70/20/10 for QB, with an 8% QB projection-bias correction), season-long talent variance, shared team boom/bust, position-specific weekly variance, injury hazard from games missed and age, optimal weekly lineups, real playoff bracket. Acceptance: history of accepted trades in these managers’ leagues (value over replacement) plus FantasyCalc and the weekly trade-value chart, refit on your recorded offer outcomes. Differences under about 1 point are noise.</p></div>`}
const renderBeforeModel=render;render=function(){try{renderBeforeModel()}catch(e){if(currentView!=='model')throw e}modelButton.classList.toggle('active',currentView==='model');modelButton.setAttribute('aria-pressed',String(currentView==='model'));if(currentView==='model')mRender()};
// Trade builder hook: title odds and acceptance for the drafted offer.
if(typeof dEvaluate==='function'){const evalBeforeModel=dEvaluate;dEvaluate=function(){evalBeforeModel();const el=$('desk-evaluation');if(!el)return;if(!modelData){el.insertAdjacentHTML('beforeend','<p><button onclick="setView(\'model\');mRequest()">Load the title model</button> to see title-odds change and acceptance odds.</p>');return}el.insertAdjacentHTML('beforeend','<p><button onclick="mEvalDraft()">Run title model on this offer</button> <span id="model-draft"></span></p>')}}
function mEvalDraft(){const out=$('model-draft');if(!out||!modelData)return;dRemember();const l=dLeague(),lid=l?.id;if(!modelData.leagues[lid]){out.textContent='League not in model data; refresh the model.';return}
 const TM=TitleModel,models=mModels(),M=models[lid],me=M.L.me,partner=deskDraft.partner,give=deskDraft.give||[],get=deskDraft.receive||[];if(!partner||!give.length||!get.length){out.textContent='Choose a partner and both sides first.';return}
 const k=TM.fitK(models,mLabels()).k,ac=TM.accept(M,give,get,0,k),E=TM.engine(M),acc={},N=6000;out.textContent='Simulating…';
 mChunks(n=>TM.simulate(M,E,[{name:'base'},{name:'offer',moves:[...give.map(p=>[p,partner]),...get.map(p=>[p,me])]}],n,acc,5),N,500,()=>{const a=acc.res[0],b=acc.res[1];out.innerHTML=`Willingness score <b>${Math.round(ac.p*100)}/100 (uncalibrated)</b> · Title ${mPct(a.title/a.n)} → <b>${mPct(b.title/b.n)}</b> · #1 seed ${mPct(a.s1/a.n)} → ${mPct(b.s1/b.n)} · Playoffs ${mPct(a.po/a.n)} → ${mPct(b.po/b.n)} (${N.toLocaleString()} seasons)`})}

document.addEventListener('keydown',e=>{if(e.metaKey&&e.key==='7'){e.preventDefault();setView('model')}});modelButton.innerHTML='Title model <kbd>⌘7</kbd>';

function modelEvidence(M){
 const inp=modelData.research_inputs||{},learn=typeof deskState!=='undefined'?deskState?.offer_learning:null;
 const owned=M.L.teams[M.L.me]?.players||[],rs=owned.map(id=>{const hist=(inp.xfp?.[id]||[]).filter(x=>x.week<modelData.week);if(!hist.length)return '';const avg=hist.reduce((sum,x)=>sum+Object.entries(M.L.score||{}).reduce((a,[key,v])=>a+(x[key]||0)*v,0),0)/hist.length;return `<tr><td>${mEsc(mName(id))}</td><td>${hist.length} games through W${Math.max(...hist.map(x=>x.week))}</td><td>${avg.toFixed(1)}</td></tr>`}).filter(Boolean);
 return dPanel('Model checks & evidence',`<p><b>Active:</b> league scoring includes kicker/defense rules; active-game variance includes talent and shared factors within one budget. Historical K/DST error distributions allow negative scores. Opponent factors are used when the NFL schedule is available. No hard ceiling is applied.</p><p><b>Still experimental:</b> betting-line point adjustments, xFP forecast blending, and coaching/rest scalars. They have not earned a change to live projections. Historical projection files may be revised after games, so retrospective improvements are provisional.</p><p>Means are treated as conditional on playing; injury absence is modeled separately. Whether the projection provider already discounts injuries is unverified. Yardage-bonus probabilities and projected defense scoring buckets remain approximations.</p><p>Offer learning: ${learn?.eligible||0} eligible dated outcomes (${learn?.accepted||0} accepted, ${learn?.rejected||0} rejected). Manager activity is descriptive; no fixed inactivity penalty or ownership premium is imposed.</p>${(inp.warnings||[]).map(w=>`<p>${mEsc(w)}</p>`).join('')}${M.L.unsupported_scoring?.length?`<p>Unsupported scoring rules: ${mEsc(M.L.unsupported_scoring.join(', '))}. Treat projections as incomplete.</p>`:''}<details><summary>Recent opportunity quality (xFP)</summary><p>Expected points from past opportunities, using supported linear league rules. Excludes nonlinear yardage bonuses, fumbles and K/DST. It is not next week’s projection. Small samples and missed games can distort averages.</p><table class="table"><tr><td>Player</td><td>Sample</td><td>xFP/game</td></tr>${rs.join('')||'<tr><td colspan="3">No opportunity data available.</td></tr>'}</table><p><a href="https://ffopportunity.ffverse.com/">ffopportunity / ffverse</a> · Data: CC BY-SA 4.0, recomputed for your scoring. <a href="https://nflreadr.nflverse.com/reference/load_schedules.html">nflverse schedules</a>.</p></details>`);
}
